ingredientes_receta = {
    "chilaquiles_verdes" : ['tortilla_de_maiz', 'aceite_vegetal', 'cebolla', 'tomates_verdes', 'chile_serrano', 'chile_jalapeño', 'cebolla_blanca', 'sal', 'orégano', 'vinagre', 'agua', 'queso_fresco', 'crema', 'cilantro', 'dientes_de_ajo'],
    "arroz_con_pollo" : ['pollo', 'arroz', 'aceite_vegetal', 'cebolla', 'pimiento', 'tomate', 'sal', 'pimienta', 'caldo_de_pollo', 'cilantro'],
    "tacos_carne_asada" : ['carne_res', 'tortilla_de_maiz', 'cebolla', 'cilantro', 'sal', 'pimienta', 'jugo_de_limon', 'aceite_vegetal'],
    "ceviche" : ['pescado_blanco', 'cebolla_roja', 'cilantro', 'aji_amarillo', 'sal', 'jugo_de_limon'],
    "tamales" : ['harina_maiz', 'cerdo', 'manteca', 'chile', 'sal', 'caldo'],
    "carne_de_res_salteada" : ['carne_res', 'arroz', 'papas', 'cebolla', 'tomate', 'aji_amarillo', 'sal', 'pimienta', 'vinagre', 'salsa_soja', 'aceite_vegetal'],
    "enchiladas_rojas" : ['tortilla_de_maiz', 'pollo', 'aceite_vegetal', 'cebolla', 'sal', 'agua', 'queso_fresco', 'crema', 'cilantro', 'dientes_de_ajo', 'chiles_secos', 'tomates'],
    "tacos_al_pastor" : ['cerdo', 'tortilla_de_maiz', 'cebolla', 'cilantro', 'piña', 'sal', 'achiote', 'chiles_secos', 'ajo', 'jugo_de_piña', 'aceite_vegetal'],
    "quesadillas_flor_calabaza" : ['tortilla_de_maiz', 'flor_calabaza', 'queso_fresco', 'aceite_vegetal', 'sal', 'ajo'],
    "enchiladas_vegetarianas" : ['tortillas_de_maiz', 'queso_fresco', 'aceite_vegetal', 'tomates_rojos', 'cebolla', 'chiles_poblanos', 'zanahorias', 'calabacitas', 'elote', 'sal', 'comino', 'cilantro'],
    "tacos_de_champiñones" : ['tortillas_de_maiz', 'aceite_vegetal', 'champiñones', 'cebolla', 'chiles_serranos', 'limones', 'sal', 'pimienta', 'cilantro', 'ajo'],
    "tacos_de_lentejas" : ['lentejas', 'tortillas_de_maiz', 'crema', 'aceite_vegetal', 'cebolla', 'tomates', 'lechuga', 'sal', 'comino'],
    "pimiento_relleno" : ['arroz_cocido', 'queso_rayado', 'pimientos_morrones', 'cebolla', 'jitomate', 'elote', 'sal', 'pimienta', 'perejil'],
    "sopa_de_tortilla" : ['tortillas_de_maiz', 'queso_fresco', 'aceite_vegetal', 'tomates_rojos', 'cebolla', 'aguacate', 'sal', 'caldo_de_verduras'],
    "molinetes_mexicanos" : ['tortillas_de_harina', 'queso_crema', 'chiles_poblanos', 'cebolla', 'sal', 'pimienta'],
    "ceviche_de_mango" : ['tostadas', 'mango', 'pepino', 'cebolla_morada', 'chiles_serranos', 'limones', 'sal', 'cilantro'],
    "picadillo_de_soya_mexicano" : ['soya_texturizada', 'aceite_vegetal', 'cebolla', 'tomates', 'papa', 'zanahoria', 'sal', 'comino', 'pimienta', 'ajo'],
    "tortitas_de_papa_rellena" : ['papas', 'pan_molido', 'aceite_vegetal', 'cebolla', 'jitomate', 'elote', 'sal', 'pimienta', 'perejil'],
    "calabacitas_al_horno" : ['queso_rayado', 'calabacitas', 'cebolla', 'jitomate', 'elote', 'sal', 'pimienta', 'epazote'],
    "coctel_de_camaron" : ['camaron', 'cilantro', 'cebolla_morada', 'chile_serrano', 'tomates_verdes', 'aguacate', 'sal_con_pimienta', 'coctel_de_tomate_con_almeja', 'jugo_de_naranja', 'jugo_de_limon', 'jugo_maggi', 'salsa_inglesa', 'salsa_picante', 'catsup', 'galletas_saladas'],
    "ensalada_de_quinoa" : ['quinoa', 'quinoa', 'pepino', 'jitomate', 'cebolla', 'pimiento_rojo', 'aceite_de_oliva', 'jugo_de_limon', 'sal', 'perejil'],
    "curry_de_garbanzos" : ['garbanzos', 'arroz_integral', 'tomate', 'cebolla', 'ajo', 'curcuma', 'comino', 'sal', 'aceite_vegetal', 'leche_de_coco', 'cilantro'],
    "hamburguesas_de_frijol_negro" : ['frijoles_negros', 'pan_integral', 'avena', 'cebolla', 'jitomate', 'lechuga', 'aguacate', 'sal', 'pimienta', 'aceite_vegetal'],
    "spaghetti_con_pure_de_berenjena" : ['tofu', 'spaghetti_integral', 'berenjena', 'ajo', 'aceite_de_oliva', 'jugo_de_limon', 'sal', 'perejil'],
    "enchiladas_de_queso" : ['queso_fresco', 'tortillas_de_maiz', 'tomate', 'chile', 'ajo', 'cebolla', 'lechuga', 'agua', 'aceite_vegetal', 'sal', 'crema'],
    "omelette_de_espinaca_y_champiñones" : ['huevo', 'pan_integral', 'espinaca', 'champiñones', 'aceite_de_oliva', 'sal', 'pimienta'],
    "lasagna_de_vegetales" : ['queso_mozzarella', 'ricotta', 'pasta_para_lasagna', 'calabacita', 'berenjena', 'zanahoria', 'espinaca', 'tomate', 'aceite_de_oliva', 'salsa_de_tomate', 'sal', 'orégano'],
    "sopa_de_brocoli_y_queso" : ['queso_cheddar', 'pan_integral', 'brocoli', 'leche', 'agua', 'sal', 'pimienta'],
    "mole poblano" : ['pollo', 'tortillas_de_maiz', 'bolillo', 'aceite_vegetal', 'cebolla', 'jitomate', 'platano_macho', 'cacahuates', 'pasas', 'chiles_mulatos', 'chiles_pasillas', 'chiles_chipotle', 'ajo', 'sal', 'canela_en_rama', 'clavos_de_olor', 'pimienta_negra', 'comino', 'caldo_de_pollo', 'almendras', 'chocolate_de_mesa', 'ajonjoli'],
    "pozole" : ['carne_de_cerdo', 'maiz_pozolero', 'tostadas', 'cebolla', 'cebolla_picada', 'lechuga', 'rábanos', 'limones', 'chiles_guajillo', 'ajos', 'agua', 'sal', 'orégano_seco'],
    "chiles en nogada" : ['carne_molida_de_cerdo', 'queso_fresco', 'leche_entera', 'cebolla', 'chiles_poblanos', 'duraznos', 'pera', 'manzana', 'granada', 'pasas', '2 dientes', 'sal', 'azúcar', 'perejil', 'almendras', 'nueces_de_castilla'],
    "cochinita pibil" : ['carne_de_cerdo', 'cebolla_morada', 'chiles_habaneros', 'sal', 'comino', 'pimienta_negra', 'orégano_seco', 'jugo_de_naranja_agria', 'vinagre_blanco', 'pasta_de_achiote', 'ajo', 'hojas_de_platano'],
    "birria" : ['carne_de_res', 'cebolla', 'cebolla', 'tomates', 'limones', 'chile_guajillo', 'chile_ancho', 'sal', 'comino', 'tomillo', 'mejorana', 'vinagre_de_manzana', 'cilantro', 'ajos', 'clavos_de_olor'],
    "huevos rancheros" : ['huevos', 'tortillas_de_maiz', 'queso_fresco', 'aceite_vegetal', 'tomates_rojos', 'cebolla', 'chiles_serranos', 'sal', 'cilantro'],
    "caldo de res" : ['carne_de_res_con_hueso', 'zanahorias', 'papas', 'calabazas', 'elote', 'repollo', 'cebolla', 'limones', 'sal', 'cilantro', 'ajos'],
    "chicharrón en salsa verde" : ['chicharrón', 'aceite_vegetal', 'tomates_verdes', 'cebolla', 'chiles_serranos', 'sal', 'cilantro', 'ajo'],
    "tacos de pescado" : ['filete_de_pescado_blanco', 'tortillas_de_maiz', 'harina_de_trigo', 'crema', 'aceite_vegetal', 'repollo', 'limones', 'sal', 'pimienta', 'polvo_para_hornear', 'cerveza_clara'],
    "albóndigas en chipotle" : ['carne_molida_de_res', 'huevo', 'pan_molido', 'cebolla', 'tomates_rojos', 'sal', 'pimienta', 'comino', 'perejil', 'chiles_chipotle_en_adobo', 'ajo'],
    "tostadas_de_tinga" : ['pollo_desmenuzado', 'jitomates', 'cebolla', 'ajo', 'lechuga', 'chile_chipotle', 'sal', 'aceite', 'tostadas', 'crema', 'queso_fresco'],
    "flautas_de_pollo" : ['pollo_desmenuzado', 'tortillas_de_maíz', 'aceite', 'lechuga', 'jitomate', 'crema', 'queso_fresco', 'sal', 'salsa'],
    "fajitas_de_pollo" : ['pollo', 'pimiento_rojo', 'pimiento_verde', 'cebolla', 'tortillas_de_maíz', 'aceite', 'sal', 'pimienta', 'ajo'],
    "sopes_mexicanos" : ['masa_de_maíz', 'carne_deshebrada', 'frijoles_refritos', 'lechuga', 'jitomate', 'crema', 'queso_fresco', 'aceite', 'salsa'],
    "enchiladas_verdes" : ['tomates_verdes', 'chile_jalapeño', 'cebolla', 'cilantro', 'pollo_desmenuzado', 'tortillas_de_maíz', 'queso_fresco', 'crema', 'aceite', 'sal'],
    "pechuga_empanizada" : ['pechugas_de_pollo', 'harina', 'pan_molido', 'huevo', 'aceite', 'sal', 'pimienta', 'lechuga', 'jitomate'],
    "chiles_rellenos" : ['chiles_poblanos', 'jitomate', 'ajo', 'cebolla', 'carne_molida (picadillo)', 'harina', 'huevo', 'aceite', 'sal', 'pimiento_verde'],
    "milanesa_de_res_con_ensalada" : ['milanesas_de_res', 'pan_molido', 'huevo', 'aceite', 'lechuga', 'jitomate', 'pepino', 'sal', 'pimienta'],
    "pollo_con_brocoli_y_zanahoria" : ['pechuga_de_pollo', 'brócoli', 'zanahoria', 'cebolla', 'aceite', 'sal', 'salsa_de_soya'],
    "tortitas_de_atun_en_salsa" : ['atun_en_lata', 'huevo', 'pan_molido', 'jitomates', 'cebolla', 'ajo', 'chile_serrano', 'perejil', 'aceite', 'sal', 'pimienta'],
}

ingredientes_picantes = {
    "poco_picante": ['chile_jalapeño', 'aji_amarrilo', 'chile_poblano'],
    "picante": ['chile_mulato', 'chile_guajillo', 'chile_ancho'],
}